// vim: set syntax=asciidoc:

:sectnums:
:toc: left

= OpenIndiana Content Creation

This is just a whiteboard for ideas.
Perhaps here you might find inspiration for things to write about.
Contributing to the Opendiana project doesn't nessessary mean you need to get involved in anything major.

.Suggestions For How to Approach Content Creation for Larger Works
While it's true there are some major projects that need love, helping out with one doesn't nessessarily mean you have to write the entire thing yourself.
- Pick a doc and tackle a single section.
- Pick a doc and add in some TODO's where they are obviously needed.
- Add new sectional placeholders where they are needed.

.Larger Works
- FAQ
- User Handbook
- Developer Handbook
- Updating the OpenSolaris books

.Smaller Works
- Writing a news story
- Writing a blog post
- Writing a tutorial

== Why a Steady Stream of Fresh Website Content is so Important

As the user comments below suggest, good docs and a steady stream of content inspires confidence in the project.
It also shows the project is alive and thriving.


.A User Comment Posted to the OI Wiki in 2011

[QUOTE]
====
Documentation such as a manual is essential in not just learning from, it tells everyone where the product is in the scheme of things.
Referring to Oracle for documentation relating to OI just makes one have less confidence with OI itself.
Look at the FreeBSD site documentation levels are really good and gives people confidence to try FreeBSD and its derivatives.
====

.A User Comment Posted to the FreeBSD Forum in 2013

[QUOTE]
====
FreeBSD has been around almost as long as Unix itself existed (not entirely true, but you get the idea) and same can be said for Solaris as it was.
Yet the OpenSolaris group basically still has to prove themselves.
For all I know (from a commercial point of view) they could be gone next month.
That makes it a liability, especially in comparison to Sun being out of the picture and the love/hate relationship with Oracle.
====


== Potentially Useful Documentation References
- https://web.archive.org/web/20081207155129/http://opensolaris.org/os/community/documentation/files/OSOLDOCSG.pdf[OpenSolaris Documentation Style Guide]
- https://web.archive.org/web/20090823064740/http://www.opensolaris.org/os/community/documentation/[docs from www.opensolaris.org]
- https://web.archive.org/web/20100909110451/http://hub.opensolaris.org/bin/view/Main/documentation[docs from hub.opensolaris.org]
- https://web.archive.org/web/20110702071619/http://cr.opensolaris.org/~gman/opensolaris-whats-new-2010-03[What's new for OSOL 2010.03]
- link to illumos graphics files: https://www.illumos.org/projects/site/files
- https://web.archive.org/web/20110904232819/http://dlc.sun.com/osol/docs/downloads/minibook/en/820-7102-10-Eng-doc.pdf[Getting Started With OpenSolaris 2008.11 - PDF minibook]
- https://www.freebsd.org/doc/en_US.ISO8859-1/books/fdp-primer/[FreeBSD Documentation Project Primer for New Contributors]


== Suggested Subjects to Write About (Tutorials, etc.)

This is just a short list of some suggested subjects to write about.
But don't limit yourself to this small list.
Write about anything you want.

.illumos and OpenIndiana HCL's
- Illumos HLC: https://www.illumos.org/hcl/


.3rd party Systems Automation
- Puppet - Hipster repo has package - version 3.6.2


.3rd party remote systems monitoring tools
- Nagios (outdated - but might be a starting point) - https://www.opencsw.org/package/nagios/


.ABI support
- Write about the change from Sun Studio to GCC its implications for ABI from previous Solaris releases/OpenSolaris, etc.
* For more details, see: http://openindiana.org/pipermail/oi-dev/2014-December/003496.html
* We might also want to talk about what other effects (if any) have/will result from the move to OI-Userland  


.Installing OI onto an ISCSI exposed SCSI target

[QOUTE]
====
  [14:50:02] <alp> does someone have some links on "installing OI on ISCSI" ?
  [14:57:40] <tsoome> alp get to illumos wiki, open projects loader -> ideas, from there you get link for jeffpc iscsi experiment
  [14:57:46] <tsoome> I did use it to play with ipxe+iscsi+loader
====

Also can look at Oracle docs for reference: https://docs.oracle.com/cd/E26502_01/html/E29008/iscsi-1.html

.Links to source code
- Talk about the links to the source code and what can be found in each repository.
* https://hg.openindiana.org/sustaining/
* https://hg.openindiana.org/upstream/

.Publishing man pages online
- Start a discussion about getting the Hipster man pages published.
* illumos core man pages are available on illumos.org
* OI specific man pages are not published. 

[QUOTE]
====
  <leoric> looking at Ubuntu dhcp.conf online man page, I thought it would be good to have automatic extractor and search interface, extracting man pages from package repository and publishing them on OI site...
  <alanc> http://illumos.org/man/ covers the illumos ones, but not all the other packages
  <leoric> I know about illumos man pages, but thought about all available man pages
  <alanc> yeah, I figured that's what you meant
  <leoric> new dhcpd seems to be working...
====
