** Editor's note:** For comparison's sake, the current FreeBSD FAQ is 78 pages (including references, etc.), written in docbook 5, stored in subversion, and is currently at revision 47,989. See: https://www.freebsd.org/doc/en_US.ISO8859-1/books/faq/book.html

= OpenIndiana FAQ

== What is OpenIndiana?

The OpenIndiana project is the open source community which develops, maintains, and supports the **https://en.wikipedia.org/wiki/OpenIndiana[OpenIndiana]** distribution, an **https://en.wikipedia.org/wiki/Illumos[illumos]** based Unix operating system derived from OpenSolaris. The OpenIndiana project is also a continuation of the collaborative effort and community spirit of the **https://en.wikipedia.org/wiki/OpenSolaris[OpenSolaris project]**. 


== Why is it called OpenIndiana?

OpenIndiana derives its name from Project Indiana, an open source effort by Sun Microsystems (now Oracle Corporation) to produce OpenSolaris, a more modern and user friendly binary Unix distribution based on Sun Solaris. To lead Project Indiana, Sun hired Ian Murdock, founder of the Debian Linux Distribution. As the successor to Solaris Express, the OpenSolaris distribution played a (Fedora like) role as an open source community testbed for what would eventually become Oracle Solaris 11.


== Is OpenIndiana a desktop or a server operating system?

As a highly capable general purpose Unix operating system, the OpenIndiana distribution is suitable for both workstations and servers. Simply pick the installer which best suits your needs (GUI or Text). OpenIndiana contains the following enterprise class features and more:

|===
|Feature |Description

| ZFS 
| **https://en.wikipedia.org/wiki/ZFS[ZFS File System and Volume Manager]**

| DTrace 
| **https://en.wikipedia.org/wiki/DTrace[Dynamic Tracing Framework - (System Introspection)]**

| Crossbow 
| **https://en.wikipedia.org/wiki/OpenSolaris_Network_Virtualization_and_Resource_Control[Network Virtualization and Resource Control]**

| SMF 
| **http://illumos.org/man/5/smf[Service Management Facility]**

| FMA 
| **http://illumos.org/man/1M/fmd[Fault Management Architecture]**

| COMSTAR 
| **http://illumos.org/man/1m/itadm[Common Multiprotocol SCSI TARget - (ISCSI Target Framework)]**

| KVM 
| **https://en.wikipedia.org/wiki/Kernel-based_Virtual_Machine[Kernel Virtual Machine - (Operating System Virtualization)]**

| Zones 
| **https://en.wikipedia.org/wiki/Solaris_Containers[OS Level Virtualized Application Containers]**

| Time-Slider 
| **http://www.serverwatch.com/tutorials/article.php/3831881/Say-Cheese-OpenSolaris-Time-Slider.htm[Automated ZFS Snapshots and Rollbacks]**

| RBAC 
| **http://www.c0t0d0s0.org/archives/4073-Less-known-Solaris-features-RBAC-and-Privileges-Part-1-Introduction.html[Role-Based Access Control]**

| IPMP 
| **http://www.c0t0d0s0.org/archives/6292-Less-known-Solaris-features-IP-Multipathing-Part-1-Introduction.html[IP Network Multipathing]**

| DLMP 
| **http://www.c0t0d0s0.org/archives/7553-Less-known-Solaris-Features-Data-Link-Multipathing.html[Data Link Multipathing]**

| Device Driver Utility 
| GUI utility for determining hardware compatibility and driver availability
|===


== Does OpenIndiana support additional keyboard layouts and languages?

Yes, when installing OpenIndiana, you may choose from 47 different keyboard layouts and 22 different languages. 


== What type of releases does OpenIndiana make available?

Approximately every six months, the OpenIndiana project releases a snapshot of the Hipster rapid development branch in the following formats:


|===
| Live DVD/USB - (Best for Desktops) | Text Install DVD/USB  - (Best for Servers)

| Gnome desktop 
| Text based console
|===


* To access our download site, please see: **http://openindiana.org/download**.
* For additional mirrors, please see: **http://wiki.openindiana.org/oi/Mirrors**.

[NOTE]
====
* Releases from the legacy oi-dev-151x branch are no longer maintained. 
** For those desiring to upgrade their legacy installations, Hipster IPS repositories are available.
** While upgrading from legacy releases is possible, the cleanest and most trouble free method is to perform a clean install.
====

CAUTION: Hipster is a rapid development branch where software versions are frequently updated. While every package is tested to ensure its stability, caution is nevertheless warranted for those intending to deploy Hipster into mission critical production environments.


== Does OpenIndiana provide security and bug fixes? 

Yes, absolutely. For the actively maintained Hipster rolling release, the OpenIndiana project seeks to ensure all known flaws are quickly mitigated. For this effort to succeed, we ask our user base to diligently bring security and bugfix concerns to our attention by submitting a ticket with the **https://www.illumos.org/projects/openindiana/issues[OpenIndiana Bug Tracker]**.


== What package manager does OpenIndiana use?

OpenIndiana uses the network based **https://en.wikipedia.org/wiki/Image_Packaging_System[Image Packaging System (IPS)]**. For those coming to OpenIndiana from BSD or Linux, the IPS package manager will be an easy transition. You may also continue to use the legacy `pkgadd/pkgrm` commands. 

[NOTE]
The OpenIndiana distribution provides a basic set of packages, along with some extras. There are also 3rd party repositories which provide additional packages. If you wish to contribute by helping to expand package availability, please read further down about how to get involved with the OpenIndiana project.

The following IPS repositories are available:


|===
| Repository Name | Repository URL | Description

| hipster-2015 
| **http://pkg.openindiana.org/hipster-2015** 
| OpenIndiana Hipster primary package repository

| hipster-encumbered 
| **http://pkg.openindiana.org/hipster-encumbered** 
| OpenIndiana Hipster encumbered license packages

| localhostoih 
| **http://sfe.opencsw.org/localhostoih** 
| 3rd party **http://sfe.opencsw.org[Spec Files Extra (SFE)]** packages
|===


To add a repository, use the following command: `pkg set-publisher -O <URL> <Repository Name>`


== What are the system hardware requirements?

|===
| | Minimum | Recommended

| **CPU** 
| 64 Bit 
| 64 Bit

| **Disk Space** 
| 20 GB 
| 40 GB +      

| **Memory (RAM)** 
| 2 GB 
| 4 GB +
|===


[NOTE]
====
* For each Terabyte of ZFS disk storage, it is recommended to add an additional 1GB of memory.
* If you intend to operate OpenIndiana with minimal memory resources, please bear in mind the default size of the OpenIndiana swapfile is 50% of installed memory. For this reason, you are strongly encouraged to increase the size of the system swap to 4 GB or more. 
====

== Are there any books or documentation to help with learning OpenIndiana?

Yes. There are several resources which will assist you with OpenIndiana. While somewhat dated now, these resources are still mostly relevant. 

* **http://www.bookfinder.com/search/?keywords=1430218916&new=&used=&ebooks=&classic=&lang=en&st=sh&ac=qr&submit=[Pro OpenSolaris]**
** A gentle and well written introduction to OpenSolaris. It weighs in at 250 pages.

* **http://www.bookfinder.com/search/?keywords=0470385480&new=&used=&ebooks=&classic=&lang=en&st=sh&ac=qr&submit=[OpenSolaris Bible]**
** A much larger and more comprehensive reference book of nearly 1000 Pages.

* **http://www.linuxtopia.org/online_books/opensolaris_2008/index.html[OpenSolaris 2008 Docs]**
** Hosted by Linuxtopia, this collection consists of over 40 books ranging from development to systems administration. These books were originally created by the OpenSolaris project and are PDL open source licensed. 

* **https://illumos.org/books/[The illumos bookshelf]**
** The illumos bookshelf consists of several original OpenSolaris advanced administration and development titles, which have been updated for illumos.


[NOTE]
====
There is a newer version of the original OpenSolaris docs (the 2009.06 drop) which the OpenIndiana documentation team is currently reviewing and updating. As each book is completed, it will be hosted on OpenIndiana.org. The documentation team is also working to produce an updated OpenIndiana handbook. If you would like to help with either of these efforts, please indicate your interest in one or more of the following ways:

* **http://openindiana.org/mailman[OpenIndiana discussion mailing list]** 
* **irc://irc.freenode.net/oi-documentation[#oi-documentation on irc.freenode.net] **
====

== How do I get involved with the OpenIndiana Project?

As a solely community supported open source software project, the success and future of OpenIndiana depends entirely on you.  The most important thing you can do is download and begin using OpenIndiana. Also, be sure to report all issues to our bug tracker. Tell your friends and coworkers about Opendiana as well. 


Below is a list of resources you may find helpful:


|===
| Resource | URL

| User Support IRC channel 
| **irc://irc.freenode.net/openindiana[#openindiana on irc.freenode.net]**

| Development IRC channel 
| **irc://irc.freenode.net/oi-dev[#oi-dev on irc.freenode.net]**

| Documentation IRC channel 
| **irc://irc.freenode.net/oi-documentation[#oi-documentation on irc.freenode.net]**

| OpenIndiana Mailing Lists 
| **http://openindiana.org/mailman**

| OpenIndiana Wiki 
| **http://wiki.openindiana.org**

| OpenIndiana Bug Tracker 
| **http://www.illumos.org/projects/openindiana/issues**
|===


If you would like to join in on all the fun, here are just some of the many ways you may contribute:

* Release engineering - Distribution Constructor
* Development
* Utilities maintenance - Image Packaging System - `pkg[5]`
* Packaging - oi-userland, 3rd party packaging (SFE, etc.)
* Documentation - Handbook, Tutorials, News articles, etc.
* OpenIndiana Evangelism - blogging, conferences, etc.
* Website Maintenance
* Translation
* Artwork


For additional details, please see: **http://www.openindiana.org/community/getting-involved**


== Is OpenIndiana a “fork” of OpenSolaris?

The goal of the OpenIndiana Project is to ensure the continued availability of an openly developed binary Unix distribution derived from OpenSolaris. 

As such, the OpenIndiana distribution is built from an assortment of source code. Some of this code was originally derived from OpenSolaris. OpenIndiana also includes code provided by the GNU project, as well as code which the Oracle Corporation continues to openly develop under the **https://opensource.org/licenses/CDDL-1.0[CDDL open-source license]**.  

Some of the differences between OpenIndiana and OpenSolaris can be characterized as follows:

* Sun/Oracle's proprietary OS/NET consolidation has been replaced with **https://github.com/OpenIndiana/illumos-gate[illumos-gate]**.
* Many of the original OpenSolaris software consolidations have been reorganized into a single **https://github.com/OpenIndiana/oi-userland[oi-userland]** consolidation.
* Oracle's Sun Studio has been replaced with the open source GNU GCC compiler - thus breaking ABI (binary) compatibility with Oracle Solaris and OpenSolaris. Please note: This change only affects applications written in C++. Applications coded in C should continue to work normally. 
* XVM (XEN) has been replaced with the illumos-kvm port.


== What is the relationship between OpenIndiana and illumos?

The **https://illumos.org[illumos project]** develops and maintains **https://github.com/illumos/illumos-gate[illumos-gate]**, the core software consolidation used in OpenIndiana. As illumos is not itself a distribution, OpenIndiana combines illumos-gate with oi-userland, and other additional free and open-source software. This melding of many different open-source software projects is somewhat analogous to how Linux distributions use the Linux kernel along with software from the GNU and various other open source projects. 


== Does OpenIndiana provide a SPARC release?

Hipster is not currently available for the SPARC platform, although there has been discussion on the **http://openindiana.org/mailman/listinfo[OpenIndiana mailing lists]** regarding the creation of a Hipster SPARC port. As for available ISO's, several years ago the OpenSolaris project released an **http://dlc.openindiana.org/isos/opensolaris[OpenSolaris text install ISO]**. And much more recently, there was work done by Adam Glassgall who produced an **http://neutron-star.mit.edu/OpenIndiana_Text_SPARC.iso[unofficial SPARC text install ISO]** based on oi-dev-151-a8. 

The following illumos based distributions are known to support the SPARC platform:

* **http://www.dilos.org/download[Dilos]**
* **http://opensxce.org[OpenSCXE]**
* **http://www.tribblix.org/download.html[Tribblix]**

For production use on modern SPARC hardware, there is also commercial **https://www.oracle.com/solaris/solaris11/index.html[Oracle Solaris]**.

If you would like to see SPARC become an OpenIndiana supported platform, please help us by joining the **http://www.openindiana.org/community/getting-involved[OpenIndiana community]**.


== How does OpenIndiana compare to BSD or Linux?

All of these operating systems follow the Unix paradigm and contain tools and commands which bear a similar resemblance, although specific feature sets and command usage may be dissimilar. If you are coming to OpenIndiana from either BSD or Linux, you will quickly learn the differences. In no time at all, you'll feel right at home working with OpenIndiana's tools and commands.


== What are the licensing terms for OpenIndiana?

OpenIndiana is composed of software from multiple different sources, each with its own licensing terms. 

For more details see:

* **https://opensource.org/licenses/CDDL-1.0[Common Development and Distribution License (CDDL-1.0)]**
* **http://illumos.org/license/PDL[PUBLIC DOCUMENTATION LICENSE (PDL), Version 1.01]**
* **https://opensource.org/licenses/MIT[The MIT License (MIT)]**
* **https://opensource.org/licenses/BSD-2-Clause[The BSD 2-Clause License]**
* **http://www.gnu.org/licenses/licenses.en.html[GNU licenses]**
