// Start of document parameters

:icons: font
:sectnums:
:toc: left

// End of document parameters

= OpenIndiana FAQ

[NOTE]
To view this doc in it's final rendered form, click the following link:
http://gist.asciidoctor.org/?github-makruger/openindiana-docs//faq.asciidoc

////
When working on this document, please bear in mind "Docs = Source Code".
In other words, treat this doc exactly as you would source code.

* Place one sentence on each line (just as you would with source code).
* This make is much easier to navigate, move lines around, add comments, etc.
* When the document is rendered by Asciidoctor, the lines will join together to form a paragraph.
* Separate paragraphs using a blank line.

=== What questions would people new to Openindiana have?

==== Where did it come from?


==== Why should people consider it?


==== What makes it different than say BSD or Linux?


==== What makes it more interesting than something else?
////


== What is OpenIndiana?

The OpenIndiana project is the open source community which develops, maintains, and supports the https://en.wikipedia.org/wiki/OpenIndiana[OpenIndiana] distribution, an https://en.wikipedia.org/wiki/Illumos[illumos] based Unix-like operating system derived from OpenSolaris.
The purpose of the OpenIndiana Project is to ensure the continued availability of an openly developed distribution based on OpenSolaris.
The OpenIndiana project is also a continuation of the collaborative effort and community spirit of the https://en.wikipedia.org/wiki/OpenSolaris[OpenSolaris project].


== Why is it called OpenIndiana?

OpenIndiana obtains its name from Project Indiana, an open source effort by Sun Microsystems (now Oracle Corporation) to produce OpenSolaris, a community developed Unix-like distribution based on Sun Solaris.
Project Indiana was led by Ian Murdock, founder of the Debian Linux Distribution.


== How are OpenIndiana and illumos related?

The https://illumos.org[illumos project] is the open source community which develops, maintains, and supports  https://github.com/illumos/illumos-gate[illumos-gate], the core software used by the OpenIndiana distribution.
Similar to a BSD `src` tree, illumos-gate includes the illumos kernel, along with many of the device drivers, core libraries, and system utilities.

To form a complete distribution, the OpenIndiana project combines illumos-gate with oi-userland, and with other free and open-source software.
This melding of software from many different open-source projects is similar to how Linux distributions use the Linux kernel along with software from the GNU and various other open source projects. 


== How does OpenIndiana differ from OpenSolaris?

Some of the differences between OpenIndiana and OpenSolaris can be characterized as follows:

* Sun/Oracle's proprietary OS/NET consolidation has been replaced with https://github.com/OpenIndiana/illumos-gate[illumos-gate].
* Many of the original OpenSolaris software consolidations have been reorganized into a single https://github.com/OpenIndiana/oi-userland[oi-userland] consolidation.
* Oracle's Sun Studio has been replaced with the open source GNU GCC compiler.
* XVM (XEN) has been replaced with the illumos-kvm port.

[NOTE]
OpenIndiana Hipster's transistion from Sun Studio to GCC has resulted in a discontinuance of ABI (binary) compatibility with previous releases of OpenIndiana, Oracle Solaris, and OpenSolaris.
Applications coded in the `C` language should continue to work normally.
Therefore, this change only affects applications written in the `C++` language.

== How does OpenIndiana compare to BSD or Linux?

All of these operating systems follow the Unix paradigm and contain tools and commands which bear a similar resemblance, although specific feature sets and command usage may be dissimilar.
If you are coming to OpenIndiana from either BSD or Linux, you will quickly learn these differences.
In no time at all, you'll feel right at home working with OpenIndiana's tools and commands.


== What features does Openindiana have?

OpenIndiana contains the following enterprise class features and more:

|===
|Feature |Description

| ZFS
| https://en.wikipedia.org/wiki/ZFS[ZFS File System and Volume Manager]

| DTrace
| https://en.wikipedia.org/wiki/DTrace[Dynamic Tracing Framework - (System Introspection)]

| Crossbow
| https://en.wikipedia.org/wiki/OpenSolaris_Network_Virtualization_and_Resource_Control[Network Virtualization and Resource Control]

| SMF
| http://illumos.org/man/5/smf[Service Management Facility]

| FMA
| http://illumos.org/man/1M/fmd[Fault Management Architecture]

| COMSTAR
| http://illumos.org/man/1m/itadm[Common Multiprotocol SCSI TARget - (ISCSI Target Framework)]

| KVM
| https://en.wikipedia.org/wiki/Kernel-based_Virtual_Machine[Kernel Virtual Machine - (Operating System Virtualization)]

| Zones
| https://en.wikipedia.org/wiki/Solaris_Containers[OS Level Virtualized Application Containers]

| Time-Slider
| http://www.serverwatch.com/tutorials/article.php/3831881/Say-Cheese-OpenSolaris-Time-Slider.htm[Automated ZFS Snapshots and Rollbacks]

| RBAC
| http://www.c0t0d0s0.org/archives/4073-Less-known-Solaris-features-RBAC-and-Privileges-Part-1-Introduction.html[Role-Based Access Control]

| IPMP
| http://www.c0t0d0s0.org/archives/6292-Less-known-Solaris-features-IP-Multipathing-Part-1-Introduction.html[IP Network Multipathing]

| DLMP
| http://www.c0t0d0s0.org/archives/7553-Less-known-Solaris-Features-Data-Link-Multipathing.html[Data Link Multipathing]

| Device Driver Utility
| GUI utility for determining hardware compatibility and driver availability
|===


== What is the OpenIndiana release schedule?

Approximately every six months, the OpenIndiana project releases a snapshot of the Hipster rolling release branch.
Ideally suited for both workstations and servers, simply pick the installer which best serves your needs:

|===
| Workstation | Server

| Live installer with Gnome desktop | Text installer with command line console
|===


[NOTE]
====
* OpenIndiana releases from the legacy oi-dev-151x branch are no longer maintained.
* For those desiring to upgrade from legacy installations, Hipster IPS repositories are available.
* While upgrades from the legacy branch are possible, the most trouble free method is to perform a clean install.
====

[CAUTION]
====
Hipster is a rapid development branch where software versions are frequently updated.
While every package is tested to ensure stability, caution is nevertheless warranted when deploying Hipster into mission critical production environments.
====

== What are the system hardware requirements?

|===
| | Minimum | Recommended

| **CPU**
| 64 Bit
| 64 Bit

| **Disk Space**
| 20 GB
| 40 GB (or more)

| **Memory (RAM)**
| 2 GB
| 4 GB (or more)
|===


[IMPORTANT]
====
Unlike Linux or Windows, where swap files are generally 100-200% of installed memory, the default size of the OpenIndiana swap file is 50% of installed memory.
For use cases where OpenIndiana is operated as a desktop, and with minimal memory resources, system swap size should be increased to 4 GB or more.
====

== Does OpenIndiana support internationalization and localization?

Yes, when installing OpenIndiana, you may choose from 47 different keyboard layouts and 22 different languages.


== Does OpenIndiana provide security and bug fixes?

Yes, absolutely.
For the actively maintained Hipster rolling release, the OpenIndiana project seeks to ensure all known flaws are quickly mitigated.
For this effort to succeed, we ask our user base to diligently bring security and bugfix concerns to our attention by submitting a ticket with the https://www.illumos.org/projects/openindiana/issues[OpenIndiana Bug Tracker].


== Where can the OpenIndiana software be obtained?

|===
| OpenIndiana Download Mirrors

| http://dlc.openindiana.org/isos/hipster[Primary Download Mirror] 
| http://ftp.vim.org/os/openindiana.org/dlc/isos/hipster[Vim.org Alternate Download Mirror]
|===

If you wish to purchase a ready made DVD or USB drive there is also https://www.osdisc.com/products/solaris/openindiana[OSDISC.COM]


== What package manager does OpenIndiana use?

OpenIndiana uses the network based https://en.wikipedia.org/wiki/Image_Packaging_System[Image Packaging System (IPS)].
For those coming to OpenIndiana from BSD or Linux, the IPS package manager will be an easy transition.
You may also continue to use the legacy `pkgadd/pkgrm` commands.

[NOTE]
The OpenIndiana distribution provides a basic set of packages, along with some extras.
There are also 3rd party repositories which provide additional packages.
If you wish to contribute by helping to expand package availability, please read further down about how to get involved with the OpenIndiana project.

The following IPS repositories are available:


|===
| Repository Name | Repository URL | Description

| hipster-2015
| http://pkg.openindiana.org/hipster-2015
| OpenIndiana Hipster primary package repository

| hipster-encumbered
| http://pkg.openindiana.org/hipster-encumbered
| OpenIndiana Hipster encumbered license packages

| localhostoih
| http://sfe.opencsw.org/localhostoih
| 3rd party http://sfe.opencsw.org[Spec Files Extra (SFE)] packages
|===


To add a repository, use the following command: `pkg set-publisher -O <URL> <Repository Name>`


== What books are available to help with learning OpenIndiana?

There are several resources which will assist you with learning to use OpenIndiana.
While somewhat dated now, these resources are largely still relevant.

* http://www.bookfinder.com/search/?keywords=1430218916&new=&used=&ebooks=&classic=&lang=en&st=sh&ac=qr&submit=[Pro OpenSolaris]
** A gentle and well written introduction to OpenSolaris. It weighs in at 250 pages.

* http://www.bookfinder.com/search/?keywords=0470385480&new=&used=&ebooks=&classic=&lang=en&st=sh&ac=qr&submit=[OpenSolaris Bible]
** A much larger and more comprehensive reference book of nearly 1000 Pages.

* https://illumos.org/books/[The illumos bookshelf]
** Updated for illumos, the illumos bookshelf consists of several original OpenSolaris advanced administration and development titles.

* http://www.linuxtopia.org/online_books/opensolaris_2008/index.html[OpenSolaris 2008 Docs]
** This online collection consists of over 40 books ranging from development to systems administration.
These books were originally created by the OpenSolaris project and are PDL open source licensed.

[NOTE]
====
In 2009, the OpenSolaris project released an updated version (the 2009.06 drop) of the OpenSolaris book collection.
This collection is currently being reviewed and updated by the OpenIndiana documentation team.
As each book is completed, it will be published on OpenIndiana.org.

The documentation team is also working to produce an updated OpenIndiana handbook and task based tutorials.
If you would like to help with these efforts, please indicate your interest in one or more of the following ways:

* http://openindiana.org/mailman[OpenIndiana discussion mailing list]
* irc://irc.freenode.net/oi-documentation[#oi-documentation on irc.freenode.net]
====


== How do I get involved with the OpenIndiana Project?

As a community supported open source software project, the success and future of OpenIndiana depends entirely on you.

The most important thing you can do is download and begin using OpenIndiana.
Tell your friends and coworkers about Opendiana as well.

Also, be sure to report all issues to our bug tracker.

Below is a list of OpenIndiana community resources you may find helpful:


|===
| Resource | URL

| User Support IRC channel
| irc://irc.freenode.net/openindiana[#openindiana on irc.freenode.net]

| Development IRC channel
| irc://irc.freenode.net/oi-dev[#oi-dev on irc.freenode.net]

| Documentation IRC channel
| irc://irc.freenode.net/oi-documentation[#oi-documentation on irc.freenode.net]

| OpenIndiana Mailing Lists
| http://openindiana.org/mailman

| OpenIndiana Wiki
| http://wiki.openindiana.org

| OpenIndiana Bug Tracker
| http://www.illumos.org/projects/openindiana/issues
|===


Here are just some of the many ways you may contribute:

* Artwork
* Development
* Documentation - Handbook, Tutorials, News articles, etc.
* Evangelism - blogging about OpenIndiana, attending conferences, etc.
* Packaging - oi-userland, 3rd party packaging (SFE, etc.)
* Release engineering
* Translation
* Utilities maintenance - Image Packaging System - `pkg[5]`
* Website Maintenance

And many, many more. Just ask on the IRC channels or mailing lists about how you may contribute.

For additional details, including links to our github source repositories, please see: http://www.openindiana.org/community/getting-involved


== Does OpenIndiana provide a SPARC release?

OpenIndiana Hipster is not currently available for the SPARC platform.

In regards to the creation of a SPARC port of OpenIndiana Hipster, there have been periodic discussions on the http://openindiana.org/mailman/listinfo[OpenIndiana mailing lists].
If you would like to see SPARC become a supported platform, please help us by joining the http://www.openindiana.org/community/getting-involved[OpenIndiana community].

=== Historical SPARC releases
In 2009, the OpenSolaris project released an http://dlc.openindiana.org/isos/opensolaris[OpenSolaris text install ISO], and much more recently, there was work done by Adam Glassgall who produced an http://neutron-star.mit.edu/OpenIndiana_Text_SPARC.iso[unofficial SPARC text install ISO] based on oi-dev-151-a8. 

=== illumos distributions with SPARC releases
The following illumos based distributions are known to support the SPARC platform:

* http://www.dilos.org/download[Dilos]
* http://opensxce.org[OpenSCXE]
* http://www.tribblix.org/download.html[Tribblix]

=== Commercial distributions with SPARC releases
For production use on modern SPARC hardware, there is also commercial https://www.oracle.com/solaris/solaris11/index.html[Oracle Solaris].


== What are the licensing terms for OpenIndiana?

OpenIndiana is composed of software from multiple different sources, each with its own licensing terms. 

Here is a list of the most commonly used licenses:

* https://opensource.org/licenses/CDDL-1.0[Common Development and Distribution License (CDDL-1.0)]
* http://illumos.org/license/PDL[PUBLIC DOCUMENTATION LICENSE (PDL), Version 1.01]
* https://opensource.org/licenses/MIT[The MIT License (MIT)]
* https://opensource.org/licenses/BSD-2-Clause[The BSD 2-Clause License]
* http://www.gnu.org/licenses/licenses.en.html[GNU licenses]
