:toc: left

= OpenIndiana Handbook

[NOTE]
To view this doc in it's final rendered form, click the following link:
http://gist.asciidoctor.org/?github-makruger/openindiana-docs//handbook.asciidoc

== Basic outline

* Intro

* Get it
* Install it
* Use it
* Discuss it
* Extend it

* FAQ's
* Tips and Tricks

=== Pre-installation caveats and considerations
* System partitioning, Gparted, etc.
* Device Driver utility - (also how to manually install missing drivers - and where to find them if they are available)
* Network install drivers: `pkgrecv -s http://pkg.openindiana.org/hipster-2015 -d bash.p5a -a bash && sudo pkg install -nv  -g bash.p5a bash`
* Local install drivers: `pkg install -g name.p5a fmri`
* How to disable drivers at boot time (this might help fix the kernel panic we see when trying to boot OI inside KVM)
* Physical or virtual?

=== What are the post-installation caveats and considerations?
* e.g. - What kinds of things can be done with a system once installed?


=== Helpful resources for writing some of these sections

* https://web.archive.org/web/20090611234850/http://dlc.sun.com/osol/docs/downloads/minibook/en/820-7102-10-Eng-doc.pdf[ Getting Started with OpenSolaris 2008.11]
* https://web.archive.org/web/20091229232632/http://www.opensolaris.com/learn/[OpenSolaris Learn site - Wayback Machine]
* https://web.archive.org/web/20100105080516/http://dlc.sun.com/osol/docs/content/2009.06/[OpenSolaris 2009.06 docs]
* https://web.archive.org/web/20100401024945/http://www.opensolaris.com/use/OpenSolaris200906Booklet.pdf[OpenSolaris 2009.06 Booklet PDF]


:sectnums:
== Introducing OpenIndiana


=== OpenIndiana Software Releases

Approximately every six months, the OpenIndiana project releases a snapshot of the Hipster rolling release branch.
Perfectly suited for both workstations and servers, simply pick the installer which best suits your needs:

|===
| Workstation | Server

| Live installer with Gnome desktop | Text installer with command line console
|===


[NOTE]
====
* Releases from the oi-dev-151x branch are no longer maintained.
* For those desiring to upgrade legacy installations, Hipster IPS repositories are available.
* While upgrading from legacy is possible, the most trouble free method is to perform a clean install.
====

[CAUTION]
====
Hipster is a rapid development branch where software versions are frequently updated.
While every package is tested to ensure its stability, caution is nevertheless warranted for those intending to deploy Hipster into mission critical production environments.
====


=== System Requirements

|===
| | Minimum | Recommended

| **CPU**
| 64 Bit
| 64 Bit

| **Disk Space**
| 20 GB
| 40 GB +

| **Memory (RAM)**
| 2 GB
| 4 GB +
|===


[IMPORTANT]
====
Unlike Linux or Windows, where swap files are generally 100-200% of installed memory, the default size of the OpenIndiana swap file is 50% of installed memory.
For use cases where OpenIndiana is operated with minimal memory resources, system swap size should be increased to 4 GB or more.
====

=== Finding help and support

==== Local system command line help

* apropos - search the manual page names and descriptions
* find - search for files in a directory hierarchy
* info - read Info documents
* locate - find files by name
* man - an interface to the on-line reference manuals


==== Web based support resources

|===
| Resource | URL

| User Support IRC channel
| irc://irc.freenode.net/openindiana[#openindiana on irc.freenode.net]

| Development IRC channel
| irc://irc.freenode.net/oi-dev[#oi-dev on irc.freenode.net]

| Documentation IRC channel
| irc://irc.freenode.net/oi-documentation[#oi-documentation on irc.freenode.net]

| OpenIndiana Mailing Lists
| http://openindiana.org/mailman

| OpenIndiana Wiki
| http://wiki.openindiana.org

| OpenIndiana Bug Tracker
| http://www.illumos.org/projects/openindiana/issues
|===

== Preparing to Install OpenIndiana

=== Backing up data

=== Deciding where to install OpenIndiana

=== Gathering Network Information

=== Obtaining the software

|===
| Download Mirrors

| http://dlc.openindiana.org/isos/hipster[Primary Download Mirror] 
| http://ftp.vim.org/os/openindiana.org/dlc/isos/hipster[Vim.org Alternate Download Mirror]
|===

If you wish to purchase a ready made DVD or USB drive there is also https://www.osdisc.com/products/solaris/openindiana[OSDISC.COM]


=== Creating a bootable OpenIndiana DVD

* Obtain the software from the download site
* Check MD5/SHA
* Burn it to a DVD

==== Windows

==== Linux

==== OpenIndiana



=== Creating a bootable OpenIndiana USB flash drive

Requirements

* Flash drive - (2GB or larger)
* Download the OI USB install media
* Download the OI 1G header file

|===
| Operating System | Method 

| Windows | OpenSolaris Live USB Creator
| BSD/Linux/OS X | DD
| illumos/Solaris | usbcopy tool
|===

* Locate the path to your USB storage device.

|===
| Operating system | Command | Device

| illumos/Solaris | `rmformat -l` | `/dev/rdsk/c*t*d*`
| Linux | `fdisk -l` | `/dev/sd*` 
| FreeBSD | `camcontrol devlist` | `/dev/da*`
| OS X | `diskutil list` | `/dev/disk*`
|===


[WARNING]
====
* When issuing the USB copy command, be sure to specify the entire USB device. 
* Do not including any partition or slice number (e.g. use `sda`, not `sda1`; `c0t0d0`, not `c0t0d0p1`).
* Make sure you identify the correct storage device, as all data on the device will be erased.
* Make sure no filesystems located on the device are mounted prior to the next step.
** Desktops may automatically mount removable devices.
** As nessessary, select any desktop icons for the USB device and issue an 'Eject' or 'Unmount' command.
** Use the mount command to list mounted filesystems. 
** If any filesystems are located on the USB storage device, they must be unmounted.
** Use `umount <path>` to unmount a filesystem, or `rmumount <path>` on illumos/Solaris, and `diskutil unmountDisk <path>` on OS X.
====

Run the following command (as root or with appropriate privileges): 

`cat 1G.header <live USB image file> | dd bs=1024k of=<path to raw USB storage device>`


== Installing OpenIndiana


=== Booting the system


The LiveDVD installer is graphical and requires X11.
When booted, it starts a live CD session which allows you to explore and test the software prior to installation.
To install from the Live CD, click one of the desktop installer icons.
 
Although it is possible to use it over a network with SSH X forwarding if you enable SSH.

The text installer is not graphical and does not have a live environment.
When you boot it, it immediately begins the installation process.


==== Booting Physical Hardware

Insert the bootable media (DVD or USB flash drive) and boot (start/restart) your computer.
For the computer to boot from the media, you may need to specify the device by pressing the boot order hotkey.
Alternately, you may need to change the boot device order in your BIOS configuration.


==== Booting Virtual Hardware

The most efficient way to boot a virtual machine is to boot directly from the DVD ISO file.
Alternately, you may use host to guest DVD/USB passthrough to boot from physical media.


===== Virtualbox

For VirtualBox 3.2 or later: 

"Use host I/O cache" must be enabled in the emulated storage controller used by the virtual machine to successfully boot OpenIndiana.


===== Vmware Workstation Player


===== Vmware ESXI


=== The OpenIndiana Boot Menu

When you see a menu, press Enter to start OpenIndiana on your computer.
As it runs, you will be prompted with a few questions.
You should eventually be presented with a desktop. 


=== Using the Device Driver Utility

You can use the Device Driver Utility to check if your hardware requires additional drivers.


=== Installing OpenIndiana to the Hard Disk

Click on Install OpenIndiana to permanently install OpenIndiana on your computer.


=== Troubleshooting Installations

* If you do not see a menu after booting your computer with the DVD or USB device, and instead see some text and a "grub>" prompt, there may be an error in your copy of the installer, or it was created incorrectly.
* If you see a "login:" prompt after selecting your keyboard and language and no desktop appears after several seconds, there may be a problem with the drivers for your graphics hardware. 
** Please let us know via IRC or the mailing list if this happens. 
** When you contact us, please include any error messages you see on the console, as well as the output of the `svcs -xv` command.
** If possible, also include the contents of the file `/var/log/Xorg.0.log`.

== Using OpenIndiana


=== Logging into OpenIndiana

The user login for the text session is username 'jack' along with the password 'jack'.
For administrative or elevated access, prepend your commands with `pfexec`.
You may also use the `sudo` command.

You may obtain root using the `su` command along with the password 'openindiana'.


=== Nvidia driver support
* Talk about the expected behavior when booting the live CD from a system with an NVIDIA card.
* Discuss procedure for adding an NVIDIA card to a system that was using VESA or some other non-3d video driver.
* Troubleshooting - what logs to look at, manual configuration, etc. 
* Walk through NVIDIA utility screens.


=== How can the desktop be modified?
* Gnome walkthrough
* Appearance applet 
** Enabling Compiz
** Configuring font anti-aliasing


=== How does one keep the system updated and find more software?
* IPS and BEADMIN walkthroughs
* http://www.oracle.com/technetwork/articles/servers-storage-admin/o11-083-ips-basics-523756.html[Basics of Image Packaging System (IPS) - Oracle]
* http://www.oracle.com/technetwork/server-storage/solaris11/documentation/ips-one-liners-032011-337775.pdf[IPS cheat sheet PDF - Oracle]
* `pkg update -nv` for change list
* `pkg update` for actual update

* Relevant OpenSolaris IPS doc titles
** Image Packaging System Guide
** Application Packaging Developer's Guide
** OpenSolaris 2008.11 Image Packaging System Guide

* Some notes for writing the IPS pages
** Clean up and consolidate information from website and wiki about where to find additional software. 
** Need to answer the questions - Where and how can I install more software?
** Discuss the various package managers (PKGIN, IPS (PKG), etc.)
** Discuss the various repos (opencsw, sfe, pkgsrc.joyent, etc.), what's available in them, and which might break compatibility, etc.
** What is SFE? How does it differ from other repos?
** Add a page for popular available software with descriptions, etc.
** When they say IPS is network centric, they're not kidding; Packages cannot be installed locally like RPM, have to setup local network repository.
*** See: http://serverfault.com/questions/348139/how-to-manually-download-individual-files-from-the-openindiana-or-solaris-pkg
** How to additional repos, etc.
** How to compile your own software. I think there is an existing wiki page for this. Given the limited number of IPS packages currently available, this is a pretty important subject to write about.
*** Also could look here (might be outdated): http://www.inetdaemon.com/tutorials/computers/software/operating_systems/unix/Solaris/compiling_software.shtml
** How to install flash player


=== How does one perform system backups?
* Time Machine
* ZFS exports
* Bacula?


=== How does one add additional users?
* Basic system administration
* Basic Unix commands


=== How does one mount or import additional disks?
* Talk about the ZFS import command.
* Need a walkthrough of mounting options for other filesystems...NTFS, FAT, UFS, etc.


=== What other things should someone learn to best utilize OI?


=== Getting OI to play Multimedia
* How to get OI to play a DVD
* How to get flash player installed and working.
* How to get VLC installed and working.
* Codecs, etc. 
* How to use the hidden `gstreamer-properties` configuration utility.


=== Using OI as a NAS
* See: https://web.archive.org/web/20091008234550/http://developers.sun.com/openstorage/articles/opensolaris_nas.html
* Running OI as a VMware EXSI guest
** Local storage hardware is passed through to the OI guest and then shared via ISCSI, CIFS, NFS, etc.


=== Using OI as a Media server, HTPC, etc.
* http://forum.kodi.tv/showthread.php?tid=44315&page=2
* http://lightsandshapes.com/plex-on-smartos.html


=== Graphics workstation


=== Desktop Publishing system, Etc.


=== Virtualization Storage Server
* Poor man's standalone ISCSI SAN linked to a 2nd machine running VMware ESXI (2 computers required)
** A variation of this would be to run OI as an ESXI guest with local storage hardware "passed through" to OI and then subsequently share ZFS volumes via  ISCSI with the ESXI host itself. In this configuration, OI effectively becomes a SAN (1 computer required)


=== Virtualization Server
* Qemu-KVM walkthrough (Does hipster even have this package?)
** Yes, KVM is the package name
* Using VIRSH, Virt-manager, etc. (Does hipster [or any illumos distro for that matter] even have virsh or Virt-manager)
** If not, what tools are used to manage the Joyant KVM port (VMADM perhaps?)
** Virtualbox walkthrough - ditto...is there a package available?


=== Zones - running web stuff in zone, development, etc.
* Need to mention some of the changes to zone management...eg. 
** sys-unconfig gone. 
** sysding replaced syscfg
*** now have to have DNS, root password, etc. all configured inside the zone before being able to logon using `zlogin -C <zonename>`, otherwise have to do `zlogin <zonename>`. So a fair amount of stuff has changed there. 


== Developing with OpenIndiana

[NOTE] 
The book titled "Introduction to Operating Systems: A Hands-On Approach Using the OpenSolaris Project" may be a good resource for helping to complete this part of the handbook.


=== How can OI be used as a development platform?


=== What programming tools, languages, etc., are available?


=== How can OI be used to further the development of OI itself?

