=== Thoughts and Considerations for Improving OpenIndiana Documentation

[NOTE]
====
Click to view this doc in its final Asciidoctor rendered form: http://gist.asciidoctor.org/?48bca1c83935b7285f52
====

==== A user comment posted to OI wiki in 2011:
* "Documentation such as a manual is essential in not just learning from, it tells everyone where the product is in the scheme of things. Referring to Oracle for documentation relating to OI just makes one have less confidence with OI itself. Look at the FreeBSD site documentation levels are really good and gives people confidence to try FreeBSD and its derivatives."


==== A comment snipped from the FreeBSD Forum in 2013
* "FreeBSD has been around almost as long as Unix itself existed (not entirely true, but you get the idea) and same can be said for Solaris as it was. Yet the OpenSolaris group basically still has to prove themselves. For all I know (from a commercial point of view) they could be gone next month. That makes it a liability, especially in comparison to Sun being out of the picture and the love/hate relationship with Oracle."


==== Some other things to think about


As a general thought....seems like it would be a good idea for the OI project to begin distancing itself from both Oracle and it's OpenSolaris roots. 

What I mean is it's almost kind of pointless to keep talking about OI being a fork of now deceased OpenSolaris, or rehashing the events which led to the birth of OI. At some point OpenIndiana needs to stand on it's own merits, not that of it's legacy. Maybe it would be best to simply say OI is an Illumos based distribution and say no more.  Perhaps another way to say this would be to suggest OI needs to look only forward now and not back at what was or could have been. [makruger]

//[The reason is that the website's content has not been update aside from the few pages I modified during the update - alarcher ]//


==== Useful references
* https://web.archive.org/web/20081207155129/http://opensolaris.org/os/community/documentation/files/OSOLDOCSG.pdf[ OpenSolaris Documentation Style Guide -(from wayback machine)]
* https://web.archive.org/web/20090823064740/http://www.opensolaris.org/os/community/documentation/[Old OpenSolaris Docs website - (from wayback machine)]
* link to illumos graphics files: https://www.illumos.org/projects/site/files
* https://web.archive.org/web/20110904232819/http://dlc.sun.com/osol/docs/downloads/minibook/en/820-7102-10-Eng-doc.pdf[ Getting StartedWith OpenSolaris 2008.11 - (PDF minibook - from wayback machine)]
* https://www.freebsd.org/doc/en_US.ISO8859-1/books/fdp-primer/[FreeBSD Documentation Project Primer for New Contributors]


=== Subjects to write about (Tutorials, etc.)

* Illumos HLC: https://www.illumos.org/hcl/


==== 3rd party Systems Automation
** Puppet - Hipster repo has package - version 3.6.2


==== 3rd party remote systems monitoring tools
* Nagios (outdated - but might be a starting point) - https://www.opencsw.org/package/nagios/


==== Write about ABI support and how the change from Sun Studio to GCC has broken ABI from previous Solaris releases/OpenSolaris, etc.

* For more details, see: http://openindiana.org/pipermail/oi-dev/2014-December/003496.html

We might also want to talk about what other effects (if any) have/will result from the move to OI-Userland  


==== Write about installing OI onto ISCSI exposed SCSI target

* Snipped from OI-DEV IRC channel
====
  [14:50:02] <alp> does someone have some links on "installing OI on ISCSI" ?
  [14:57:40] <tsoome> alp get to illumos wiki, open projects loader -> ideas, from there you get link for jeffpc iscsi experiment
  [14:57:46] <tsoome> I did use it to play with ipxe+iscsi+loader
====

Also can look at Oracle docs for reference: https://docs.oracle.com/cd/E26502_01/html/E29008/iscsi-1.html


=== Does OI use an /etc/release file like most linux distributions?
If not, how can someone tell what release they are on?
//[I can answer that: the package delivering this file has not been updated. As long as migration of all packages to oi-userland is not done then no cake - alarcher]//

=== Links to source code

* https://hg.openindiana.org/sustaining/
* https://hg.openindiana.org/upstream/

==== Publish man pages online
* illumos core man pages are available on illumos.org
* OI specific man pages are not published. 
* Recent Comment from OI-DEV IRC
====
  <leoric> looking at Ubuntu dhcp.conf online man page, I thought it would be good to have automatic extractor and search interface, extracting man pages from package repository and publishing them on OI site...
  <alanc> http://illumos.org/man/ covers the illumos ones, but not all the other packages
  <leoric> I know about illumos man pages, but thought about all available man pages
  <alanc> yeah, I figured that's what you meant
  <leoric> new dhcpd seems to be working...
====
