// vim: set syntax=asciidoc:

:sectnums:
:toc: left

= Improving the OpenIndiana Project


[NOTE]
====
For expert community building guidance from a seasoned OpenSolaris veteran, see Jim Grisianzio's https://jimgrisanzio.wordpress.com/communities/[communities] page.
====

== Governance Board

At this time the OpenIndiana project operates ungoverned.
As a result, reaching consensus can often be difficult.
Furthermore, without governance, there can sometimes be discord.

I propose the creation of an OpenIndiana governance board to help steer the Openindiana project and help reign in community members with troublesome behaviours.

== Code of Conduct

At this time the OpenIndiana project operates without a code of conduct.
As a result, a member of the greater OpenIndiana community could concievably conduct themselves without restraint.
Naturally this absense of order and respect would greatly disrupt the continuance and harmony of the project, affecting all members negatively.
Poorly behaving community members also cast the entire project in a negative light.
For this reason alone, an effective code of conduct (and a governance board to enforce it) are imperative.


== Public Relations
* Distrowatch
** I contacted Distrowatch to update to info to 2015.10 and provided and updated list of package version. - [alarcher] 
** Some version numbers are still incorrect.
For the next round I provided a mapping from DistroWatch to Hipster names:
http://hub.openindiana.ninja/?q=content/distrowatch-openindiana-hipster-packages[here] - [alarcher]
* http://opensolaris.linuxfreedom.com/ - didn't see OpenIndiana here anywhere (still showing OpenSolaris)
* Unixmen
* Slashdot
* Phoronix
** Even if the pertinence of such benchmarks is questionable, we should add the Phoronix Test Suite to oi-userland as indicator. - [alarcher]


== Hipster News
* Current events with OI Hipster distro
* OI/illumos news stories
* Featured new packages
* Tips and Tricks


== Other Periodic Website Updates
* Publish new pictures for the Community and update the Roadmap every 6 months


== Software wish list to make the desktop more usable

* The desktop is really what makes OI unique among all the different illumos distributions. 
** The project should really capitalize on the desktop, and by extension include lots of GUI software.
* Aim not just for parity with PC-BSD or FreeBSD, but usability parity with Linux Mint.


=== Alternate Desktops
* http://mate-desktop.com/[Mate]
* https://www.kde.org/[KDE]
* https://github.com/linuxmint/Cinnamon[Cinnamon]

=== Audio/Video Editing
* http://www.audacityteam.org/[Audacity]
* https://handbrake.fr/[Handbrake]

=== Benchmarking tools
* http://www.phoronix-test-suite.com/[Phoronix Test Suite]

=== Development tools
* https://atom.io/[ATOM - Text Editor]
* http://www.vim.org/[GVIM - Text Editor]
* https://eclipse.org/[Eclipse - IDE]
* http://meldmerge.org/[Meld - Diff Viewer]
* https://www.sublimetext.com/3[Sublime - Text Editor]

=== Desktop publishing
* http://www.scribus.net/[Scribus]
* https://inkscape.org/en/[Inkscape]
* https://www.calligra.org/[Calligra Suite]

=== Ebook Tools
* https://calibre-ebook.com/[Calibre]

=== File Backup
* https://www.code42.com/crashplan/[CrashPlan]

=== File Sharing
* http://deluge-torrent.org/[Deluge]

=== File Storage
* http://www.dropbox.com[dropbox]

=== Graphics
* https://www.blender.org/[Blender]
* https://krita.org/[Krita]
* http://www.xaraxtreme.org/[Xara]
* http://www.povray.org/[POV-Ray]
* http://www.radiance-online.org/[Radiance]

=== Photography
* http://www.darktable.org/[Darktable]
* http://rawtherapee.com/[RawTherapee]
* https://www.digikam.org/[Digikam]
* http://hugin.sourceforge.net/[Hugin]
* https://picasa.google.com/[Picasa]

=== Virtualization - OpenIndiana as a Host
* https://virt-manager.org/[Virt-Manager]
* http://www.ovirt.org/[O-virt]
* https://www.virtualbox.org/[Virtualbox]

=== Virtualization - OpenIndiana as a Guest
* http://www.spice-space.org/[Native Spice Protocol Support for an OpenIndiana Guest OS]
* https://my.vmware.com/web/vmware/details?productId=491&downloadGroup=VMTOOLS1000[Native Vmware tools support for an OpenIndana Guest OS]

=== Web browsers
* http://www.chromium.org/Home[Chromium]

=== Suggestions for improving elements of the distro itself
* Updated Custom desktop background for OI - Perhaps downloads from the website, or included in distro.
* Updated Custom splash screen for grub (or Forth bootloader)

