// vim: set syntax=asciidoc:


= openindiana-docs

This repository is for the development of OpenIndiana systems documentation as well as additional work products to help promote and improve all areas of the OpenIndiana project.
Below you will find a stylized link to each file along with a brief summary of its content.


// Looking at the Structure of the BSD Handbooks
== http://gist.asciidoctor.org/?github-makruger/openindiana-docs//bsd_handbooks.adoc[Looking at the Structure of the BSD Handbooks]
TOC outlines for the FreeBSD and PCBSD handbooks for help with developing an OpenIndiana handbook.
Also provides some information about how documentation and other content are delivered, toolsets used, etc.


// Building a Document Management Toolchain using Sphinx
== http://gist.asciidoctor.org/?github-makruger/openindiana-docs//sphinx_toolchain.adoc[Building a Document Management Toolchain using Sphinx]
Guidance and web-links for the development of a Sphinx based continuous integration documentation toolchain.
Sphinx is python based documentation framework and uses RestructuredTEXT as the text markup language.

// Building a Continuous Integration Content Management Toolchain
== http://gist.asciidoctor.org/?github-makruger/openindiana-docs//cicm_toolchain.adoc[Building a Continuous Integration Content Management Toolchain]
General discussion of ideas leading to the development of a text markup based continuous integration content management toolchain.
Discusses Asciidoctor, a Ruby based documentation framework using Asciidoc as the text markup language.
Taking the idea of a documentation management toolchain to the next level, looks at content delivery systems and practices as a whole.
Also discusses moving away from database driven CMS systems in exchange for a static HTML web presences where the source lives in GitHub and deploys upon commit.


// Improving OpenIndiana Systems Documentation
== http://gist.asciidoctor.org/?github-makruger/openindiana-docs//content_creation.adoc[OpenIndiana Content Creation]
This page is a whiteboard of ideas, suggestions, and movitations for how to get started with content creation.

// Improving the OpenIndiana Project
== http://gist.asciidoctor.org/?github-makruger/openindiana-docs//project_improvements.adoc[Improving the OpenIndiana Project]
General discussion of ideas to further improve and promote the OpenIndiana project.
Also contains a wish list of software to enhance the utility of OpenIndiana Hipster as a desktop operating system.


// Improving the OpenIndiana Wiki]
== http://gist.asciidoctor.org/?github-makruger/openindiana-docs//wiki_improvements.adoc[Improving the OpenIndiana Wiki]
General discussion and suggestions for improving the OpenIndiana Wiki website.


// Improving the OpenIndiana Website]
== http://gist.asciidoctor.org/?github-makruger/openindiana-docs//website_improvements.adoc[Improving the OpenIndiana Website]
General discussion and suggestions for improving the OpenIndiana Wordpress (Primary) website.


// The OpenSolaris Redistributable Books
== http://gist.asciidoctor.org/?github-makruger/openindiana-docs//opensolaris_books.adoc[The OpenSolaris Redistributable Books]
Information about the OpenSolaris book collections (2008.11 and 2009.09.15, etc.)


// The OpenIndiana FAQ
== http://gist.asciidoctor.org/?github-makruger/openindiana-docs//openindiana_faq.adoc[The OpenIndiana FAQ]
The OpenIndiana FAQ - Still a work in progress.
Not a technical FAQ as it only answers general questions about the project and it's software.


// The OpenIndiana Handbook
== http://gist.asciidoctor.org/?github-makruger/openindiana-docs//openindiana_handbook.adoc[The OpenIndiana Handbook]
The OpenIndiana Handbook - Still a work in progress.
This document is a basic HOWTO guide for new users unfamiliar with OpenIndinana Hipster.


