// vim: set syntax=asciidoc:

:sectnums:
:toc: left

= Improving the OpenIndiana Wiki


== Wiki Usability on Mobile Devices

The OpenIndiana Wiki does not render well on mobile devices.

- The left hand navigation menu is completely absent when browsing the wiki from Android phones and tablets.

Possible solutions:

- Add in page navigation menus
- Replace the wiki with a mobile aware wiki
- Replace the wiki with a user forum
- Replace the wiki as part of a larger web presence transformation


== Need to Create a Wiki Style Guide

Should the Wiki be retained, it may be helpful to create a Wiki style guide.
This would be very helpful by ensuring consistency between the different pages.
It may also be helpful to modify the existing CSS to help improve the athestics of the site.

.Possible suggestions
- This would be very helpful for providing some consistency between different pages.
* Use horizontal lines (top and bottom) to separate code blocks from the text body.
** Makes it easier to tell what is or isn't code. 
Also provides for a more efficient use of space (don't have to use so many line breaks).
- Develop standards for displaying certain types of information...e.g. code blocks, commands, tips, warnings, info, etc. 
- consider whether it's possible to enable wiki page navigation by placing breadcrumbs navigational elements within the page itself, rather than relying entirely on Wiki navigation menu in left hand navigation pane.


- Can look at other Illumos wikis for ideas and inspiration
* https://wiki.smartos.org/display/DOC/Doc+Team+Notes
* http://omnios.omniti.com/wiki.php/WikiStart
* http://wiki.illumos.org/display/illumos/illumos+Home



== Some notes for updating wiki pages

While replacing the Wiki with some kind of continuous integration content management system would likely be the most ideal solution, there are still things which can be done to help improve the wiki.

.Clean up old user comments
- Many, many comments from 2010 - 2012. 
* Probably a good idea to clean these up and incorporated the information into the page as appropriate.
* Comments with such old timestamps suggests little site activity has occurred in last 4-5 years.


.Mark old pages for deprication
- Go through the wiki and mark content as obsolete.
- Retain items of value and either pull them into the new handbook (if it's helpful for new users), or set it aside for reference when updating the OpenSolaris books.
- Reorganize things which are not being moved.

